name: Build and Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for NPM
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: '9.15.0'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build package
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    #   - name: Setup Node.js for GitHub Packages
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: 'lts/*'
    #       registry-url: 'https://npm.pkg.github.com'
    #       scope: '@lixpi'

    #   - name: Publish to GitHub Packages
    #     run: pnpm publish --registry=https://npm.pkg.github.com --no-git-checks
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
